import uuid
from typing import TYPE_CHECKING, Any

from pgvector.sqlalchemy import Vector
from sqlalchemy import ForeignKey, Text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.infrastructure.database.sqlalchemy.postgresql.base import Base

if TYPE_CHECKING:
    from app.infrastructure.database.sqlalchemy.postgresql.models.document import (
        Document,
    )


class DocumentChunk(Base):
    """Represents a text chunk of a document with its vector embedding."""

    __tablename__ = "document_chunks"

    document_id: Mapped[uuid.UUID] = mapped_column(
        # FK to the parent document this chunk belongs to
        ForeignKey("documents.id", ondelete="CASCADE"),
        nullable=False,
    )
    chunk: Mapped[str] = mapped_column(
        # The text content of this chunk
        Text,
        nullable=False,
    )
    embedding: Mapped[list[float]] = mapped_column(
        # 1536-dimensional vector embedding generated by text-embedding-3-small
        Vector(1536),
        nullable=False,
    )
    metadata_: Mapped[dict[str, Any]] = mapped_column(
        # Arbitrary key-value metadata for filtering
        "metadata",
        JSONB,
        nullable=False,
        server_default="{}",
    )

    document: Mapped[Document] = relationship(back_populates="chunks")
